import React, { useEffect, useState, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Card,
  CardContent,
  Chip,
  FormControl,
  InputLabel,
  MenuItem,
  Paper,
  Select,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  TableSortLabel,
  Typography,
  CircularProgress,
  Alert,
  Button,
  IconButton,
  Toolbar,
  AppBar,
  Switch,
} from '@mui/material';
import ClearIcon from '@mui/icons-material/Clear';
import Brightness4Icon from '@mui/icons-material/Brightness4';
import Brightness7Icon from '@mui/icons-material/Brightness7';
import { patientApi, PatientMonitoringItem } from '../services/api';

type SortField = keyof PatientMonitoringItem | '';
type SortDirection = 'asc' | 'desc';

interface DashboardProps {
  mode: 'light' | 'dark';
  setMode: (mode: 'light' | 'dark') => void;
}

const Dashboard: React.FC<DashboardProps> = ({ mode, setMode }) => {
  const navigate = useNavigate();
  const [allPatients, setAllPatients] = useState<PatientMonitoringItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(50);
  const [hoursThreshold, setHoursThreshold] = useState(48);
  const [selectedDepartments, setSelectedDepartments] = useState<string[]>([]);
  const [selectedAgeBins, setSelectedAgeBins] = useState<string[]>([]);
  const [selectedPhysicians, setSelectedPhysicians] = useState<string[]>([]);
  const [selectedLastTests, setSelectedLastTests] = useState<string[]>([]);
  const [sortField, setSortField] = useState<SortField>('');
  const [sortDirection, setSortDirection] = useState<SortDirection>('asc');

  const fetchPatients = async () => {
    setLoading(true);
    setError(null);
    try {
      // Fetch all patients by getting all pages (always use 48h threshold, filter client-side)
      const allPatientsData: PatientMonitoringItem[] = [];
      let page = 1;
      const pageSize = 1000;
      let hasMore = true;

      while (hasMore) {
        const response = await patientApi.getMonitoring(
          48, // Always fetch with 48h threshold, we'll filter client-side
          undefined, // No department filter - we'll do it client-side
          page,
          pageSize
        );
        
        allPatientsData.push(...response.data);
        
        // Check if we've fetched all patients
        const totalFetched = allPatientsData.length;
        const totalAvailable = response.pagination.total;
        
        if (totalFetched >= totalAvailable || response.data.length < pageSize) {
          hasMore = false;
        } else {
          page++;
        }
      }

      setAllPatients(allPatientsData);
      if (allPatientsData.length === 0) {
        setError('No patients found. Make sure snapshots have been generated by running: python -m backend.app.db.snapshot_builder');
      }
    } catch (err) {
      console.error('Error fetching patients:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch patients');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPatients();
  }, []); // Only fetch once on mount

  // Get unique values for filters
  const physicians = useMemo(() =>
    Array.from(new Set(allPatients.map((p) => p.primary_physician).filter((p): p is string => Boolean(p)))).sort(),
    [allPatients]
  );
  const lastTests = useMemo(() =>
    Array.from(new Set(allPatients.map((p) => p.last_test_name).filter((t): t is string => Boolean(t)))).sort(),
    [allPatients]
  );

  // Age bin helper
  const getAgeBin = (age: number | null): string => {
    if (age === null) return 'Unknown';
    if (age < 18) return '0-17';
    if (age < 30) return '18-29';
    if (age < 45) return '30-44';
    if (age < 60) return '45-59';
    if (age < 75) return '60-74';
    return '75+';
  };

  const ageBins = ['0-17', '18-29', '30-44', '45-59', '60-74', '75+', 'Unknown'];

  // Helper to parse duration string to hours
  const parseDurationToHours = (duration: string | null): number => {
    if (!duration || duration === 'N/A' || duration === 'No tests') return 0;
    let totalHours = 0;
    const hoursMatch = duration.match(/(\d+)h/);
    if (hoursMatch) {
      totalHours += parseInt(hoursMatch[1], 10);
    }
    const daysMatch = duration.match(/(\d+)d/);
    if (daysMatch) {
      totalHours += parseInt(daysMatch[1], 10) * 24;
    }
    const weeksMatch = duration.match(/(\d+)w/);
    if (weeksMatch) {
      totalHours += parseInt(weeksMatch[1], 10) * 24 * 7;
    }
    const yearsMatch = duration.match(/(\d+)y/);
    if (yearsMatch) {
      totalHours += parseInt(yearsMatch[1], 10) * 24 * 365;
    }
    return totalHours;
  };

  const computeAlertStatus = useCallback(
    (patient: PatientMonitoringItem): boolean => {
      if (!patient.time_since_last_test || patient.time_since_last_test === 'No tests') {
        return true;
      }
      if (patient.time_since_last_test === 'N/A') {
        return true;
      }
      const hoursSinceLastTest = parseDurationToHours(patient.time_since_last_test);
      return hoursSinceLastTest >= hoursThreshold;
    },
    [hoursThreshold]
  );

  // Filter and sort patients
  const filteredAndSortedPatients = useMemo(() => {
    let filtered = [...allPatients];

    // Apply filters
    if (selectedDepartments.length > 0) {
      filtered = filtered.filter((p) => p.department && selectedDepartments.includes(p.department));
    }
    if (selectedAgeBins.length > 0) {
      filtered = filtered.filter((p) => {
        const bin = getAgeBin(p.age);
        return selectedAgeBins.includes(bin);
      });
    }
    if (selectedPhysicians.length > 0) {
      filtered = filtered.filter((p) => p.primary_physician && selectedPhysicians.includes(p.primary_physician));
    }
    if (selectedLastTests.length > 0) {
      filtered = filtered.filter((p) => p.last_test_name && selectedLastTests.includes(p.last_test_name));
    }

    // Apply sorting
    if (sortField) {
      filtered.sort((a, b) => {
        let aVal: any = a[sortField];
        let bVal: any = b[sortField];

        // Handle null/undefined values
        if (aVal === null || aVal === undefined) aVal = '';
        if (bVal === null || bVal === undefined) bVal = '';

        // Special handling for datetime columns
        if (sortField === 'admission_datetime' || sortField === 'last_test_datetime') {
          const parseDateTime = (dt: string | null): number => {
            if (!dt || dt === 'N/A') return 0;
            // Format: "d.m.yyyy HH:MM:SS" or "d.m.yyyy HH:MM"
            try {
              const cleaned = dt.replace(/:\d{2}$/, ''); // Remove seconds if present
              const [datePart, timePart] = cleaned.split(' ');
              if (!datePart || !timePart) return 0;
              const [day, month, year] = datePart.split('.');
              const [hour, minute] = timePart.split(':');
              const date = new Date(
                parseInt(year, 10),
                parseInt(month, 10) - 1,
                parseInt(day, 10),
                parseInt(hour, 10),
                parseInt(minute, 10)
              );
              return date.getTime();
            } catch {
              return 0;
            }
          };
          const aTime = parseDateTime(aVal);
          const bTime = parseDateTime(bVal);
          return sortDirection === 'asc' ? aTime - bTime : bTime - aTime;
        }

        // Special handling for duration columns
        if (sortField === 'admission_length' || sortField === 'time_since_last_test') {
          const aHours = parseDurationToHours(aVal);
          const bHours = parseDurationToHours(bVal);
          return sortDirection === 'asc' ? aHours - bHours : bHours - aHours;
        }

        // Handle different types
        if (typeof aVal === 'number' && typeof bVal === 'number') {
          return sortDirection === 'asc' ? aVal - bVal : bVal - aVal;
        }
        if (typeof aVal === 'string' && typeof bVal === 'string') {
          return sortDirection === 'asc' 
            ? aVal.localeCompare(bVal)
            : bVal.localeCompare(aVal);
        }

        // Convert to string for comparison
        const aStr = String(aVal);
        const bStr = String(bVal);
        return sortDirection === 'asc' 
          ? aStr.localeCompare(bStr)
          : bStr.localeCompare(aStr);
      });
    }

    return filtered;
  }, [
    allPatients,
    selectedDepartments,
    selectedAgeBins,
    selectedPhysicians,
    selectedLastTests,
    sortField,
    sortDirection,
  ]);

  const totalAlerts = useMemo(
    () => allPatients.filter((p) => computeAlertStatus(p)).length,
    [allPatients, computeAlertStatus]
  );

  // Department summary - always show all departments from all patients
  const departmentSummary = useMemo(() => {
    const summary: Record<string, { total: number; filtered: number }> = {};
    allPatients.forEach((p) => {
      const dept = p.department || 'Unknown';
      if (!summary[dept]) {
        summary[dept] = { total: 0, filtered: 0 };
      }
      summary[dept].total++;
    });
    filteredAndSortedPatients.forEach((p) => {
      const dept = p.department || 'Unknown';
      if (summary[dept]) {
        summary[dept].filtered++;
      }
    });
    return summary;
  }, [allPatients, filteredAndSortedPatients]);

  // Pagination
  const paginatedPatients = useMemo(() => {
    const start = page * rowsPerPage;
    return filteredAndSortedPatients.slice(start, start + rowsPerPage);
  }, [filteredAndSortedPatients, page, rowsPerPage]);

  const handleSort = (field: SortField) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('asc');
    }
  };

  const formatDateTime = (dateTime: string | null): string => {
    if (!dateTime) return 'N/A';
    return dateTime.replace(/:\d{2}$/, '');
  };

  const getDurationColor = (duration: string | null): 'default' | 'error' | 'warning' | 'info' => {
    if (!duration || duration === 'N/A' || duration === 'No tests') return 'default';
    let totalHours = 0;
    const hoursMatch = duration.match(/(\d+)h/);
    if (hoursMatch) {
      totalHours += parseInt(hoursMatch[1], 10);
    }
    const daysMatch = duration.match(/(\d+)d/);
    if (daysMatch) {
      totalHours += parseInt(daysMatch[1], 10) * 24;
    }
    const weeksMatch = duration.match(/(\d+)w/);
    if (weeksMatch) {
      totalHours += parseInt(weeksMatch[1], 10) * 24 * 7;
    }
    const yearsMatch = duration.match(/(\d+)y/);
    if (yearsMatch) {
      totalHours += parseInt(yearsMatch[1], 10) * 24 * 365;
    }
    if (totalHours > 72) return 'error';
    if (totalHours > 48) return 'warning';
    return 'info';
  };

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}>
      <AppBar position="static" elevation={0} sx={{ bgcolor: 'primary.main', mb: 3 }}>
        <Toolbar>
          <Typography variant="h5" component="div" sx={{ flexGrow: 1, fontWeight: 600 }}>
            Patient Monitoring System
          </Typography>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Brightness7Icon sx={{ color: 'white' }} />
            <Switch
              checked={mode === 'dark'}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setMode(e.target.checked ? 'dark' : 'light')}
              sx={{
                '& .MuiSwitch-switchBase.Mui-checked': {
                  color: 'white',
                },
                '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track': {
                  backgroundColor: 'rgba(255, 255, 255, 0.5)',
                },
              }}
            />
            <Brightness4Icon sx={{ color: 'white' }} />
            <Typography sx={{ color: 'white', ml: 1 }}>
              {mode === 'dark' ? 'Dark' : 'Light'} Mode
            </Typography>
          </Box>
        </Toolbar>
      </AppBar>

      <Box sx={{ p: 3 }}>

      <Box sx={{ mb: 3, display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'flex-start' }}>
        <FormControl sx={{ minWidth: 150 }}>
          <InputLabel>Alert threshold</InputLabel>
          <Select
            value={hoursThreshold}
            label="Alert threshold"
            onChange={(e) => {
              setHoursThreshold(Number(e.target.value));
              setPage(0);
            }}
          >
            <MenuItem value={48}>48 hours</MenuItem>
            <MenuItem value={72}>72 hours</MenuItem>
            <MenuItem value={96}>96 hours</MenuItem>
          </Select>
        </FormControl>

        <FormControl sx={{ minWidth: 150 }}>
          <InputLabel>Age</InputLabel>
          <Select
            multiple
            value={selectedAgeBins}
            label="Age"
            onChange={(e) => {
              setSelectedAgeBins(typeof e.target.value === 'string' ? [e.target.value] : e.target.value);
              setPage(0);
            }}
            renderValue={(selected) => (selected as string[]).join(', ')}
            endAdornment={
              selectedAgeBins.length > 0 && (
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedAgeBins([]);
                    setPage(0);
                  }}
                  sx={{ mr: 1 }}
                >
                  <ClearIcon fontSize="small" />
                </IconButton>
              )
            }
          >
            {ageBins.map((bin) => (
              <MenuItem key={bin} value={bin}>
                {bin}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <FormControl sx={{ minWidth: 200 }}>
          <InputLabel>Primary Physician</InputLabel>
          <Select
            multiple
            value={selectedPhysicians}
            label="Primary Physician"
            onChange={(e) => {
              setSelectedPhysicians(typeof e.target.value === 'string' ? [e.target.value] : e.target.value);
              setPage(0);
            }}
            renderValue={(selected) => (selected as string[]).join(', ')}
            endAdornment={
              selectedPhysicians.length > 0 && (
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedPhysicians([]);
                    setPage(0);
                  }}
                  sx={{ mr: 1 }}
                >
                  <ClearIcon fontSize="small" />
                </IconButton>
              )
            }
          >
            {physicians.map((physician) => (
              <MenuItem key={physician} value={physician}>
                {physician}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <FormControl sx={{ minWidth: 200 }}>
          <InputLabel>Last Test</InputLabel>
          <Select
            multiple
            value={selectedLastTests}
            label="Last Test"
            onChange={(e) => {
              setSelectedLastTests(typeof e.target.value === 'string' ? [e.target.value] : e.target.value);
              setPage(0);
            }}
            renderValue={(selected) => (selected as string[]).join(', ')}
            endAdornment={
              selectedLastTests.length > 0 && (
                <IconButton
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    setSelectedLastTests([]);
                    setPage(0);
                  }}
                  sx={{ mr: 1 }}
                >
                  <ClearIcon fontSize="small" />
                </IconButton>
              )
            }
          >
            {lastTests.map((test) => (
              <MenuItem key={test} value={test}>
                {test}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <Button
          variant="outlined"
          onClick={() => {
            setSelectedDepartments([]);
            setSelectedAgeBins([]);
            setSelectedPhysicians([]);
            setSelectedLastTests([]);
            setHoursThreshold(48);
            setPage(0);
          }}
          disabled={
            selectedDepartments.length === 0 &&
            selectedAgeBins.length === 0 &&
            selectedPhysicians.length === 0 &&
            selectedLastTests.length === 0 &&
            hoursThreshold === 48
          }
        >
          Clear All Filters
        </Button>
      </Box>

      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
            <Typography variant="h6" sx={{ fontWeight: 600 }}>
              {filteredAndSortedPatients.length} patients ({totalAlerts} alerts total)
            </Typography>
          </Box>
          
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
            {Object.entries(departmentSummary)
              .sort((a, b) => a[0].localeCompare(b[0]))
              .map(([dept, counts]) => {
                const isSelected = selectedDepartments.includes(dept);
                return (
                  <Chip
                    key={dept}
                    label={`${dept}: ${counts.filtered}/${counts.total}`}
                    color={isSelected ? 'primary' : 'default'}
                    variant={isSelected ? 'filled' : 'outlined'}
                    size="small"
                    onClick={() => {
                      if (isSelected) {
                        setSelectedDepartments(selectedDepartments.filter((d) => d !== dept));
                      } else {
                        setSelectedDepartments([...selectedDepartments, dept]);
                      }
                      setPage(0);
                    }}
                    onDelete={
                      isSelected
                        ? () => {
                            setSelectedDepartments(selectedDepartments.filter((d) => d !== dept));
                            setPage(0);
                          }
                        : undefined
                    }
                    sx={{ cursor: 'pointer' }}
                  />
                );
              })}
          </Box>
        </CardContent>
      </Card>

      <Card>
        <CardContent>
          {loading ? (
            <Box sx={{ display: 'flex', justifyContent: 'center', p: 3 }}>
              <CircularProgress />
            </Box>
          ) : error ? (
            <Alert severity="error">{error}</Alert>
          ) : (
            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'case_number'}
                        direction={sortField === 'case_number' ? sortDirection : 'asc'}
                        onClick={() => handleSort('case_number')}
                      >
                        Case #
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'name'}
                        direction={sortField === 'name' ? sortDirection : 'asc'}
                        onClick={() => handleSort('name')}
                      >
                        Name
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'age'}
                        direction={sortField === 'age' ? sortDirection : 'asc'}
                        onClick={() => handleSort('age')}
                      >
                        Age
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'department'}
                        direction={sortField === 'department' ? sortDirection : 'asc'}
                        onClick={() => handleSort('department')}
                      >
                        Department
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'room_number'}
                        direction={sortField === 'room_number' ? sortDirection : 'asc'}
                        onClick={() => handleSort('room_number')}
                      >
                        Room
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'admission_datetime'}
                        direction={sortField === 'admission_datetime' ? sortDirection : 'asc'}
                        onClick={() => handleSort('admission_datetime')}
                      >
                        Admission Datetime
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'admission_length'}
                        direction={sortField === 'admission_length' ? sortDirection : 'asc'}
                        onClick={() => handleSort('admission_length')}
                      >
                        Admission Length
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'last_test_datetime'}
                        direction={sortField === 'last_test_datetime' ? sortDirection : 'asc'}
                        onClick={() => handleSort('last_test_datetime')}
                      >
                        Last Test Datetime
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'time_since_last_test'}
                        direction={sortField === 'time_since_last_test' ? sortDirection : 'asc'}
                        onClick={() => handleSort('time_since_last_test')}
                      >
                        Time Since Last Test
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'last_test_name'}
                        direction={sortField === 'last_test_name' ? sortDirection : 'asc'}
                        onClick={() => handleSort('last_test_name')}
                      >
                        Last Test
                      </TableSortLabel>
                    </TableCell>
                    <TableCell>
                      <TableSortLabel
                        active={sortField === 'primary_physician'}
                        direction={sortField === 'primary_physician' ? sortDirection : 'asc'}
                        onClick={() => handleSort('primary_physician')}
                      >
                        Primary Physician
                      </TableSortLabel>
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {paginatedPatients.map((patient) => (
                    <TableRow
                      key={patient.patient_id}
                      onClick={() => navigate(`/patient/${patient.patient_id}`)}
                      sx={{
                        cursor: 'pointer',
                        transition: 'background-color 0.2s',
                      }}
                    >
                      <TableCell>{patient.case_number}</TableCell>
                      <TableCell>{patient.name}</TableCell>
                      <TableCell>{patient.age !== null ? patient.age : 'N/A'}</TableCell>
                      <TableCell>{patient.department || 'N/A'}</TableCell>
                      <TableCell>{patient.room_number || 'N/A'}</TableCell>
                      <TableCell>{formatDateTime(patient.admission_datetime)}</TableCell>
                      <TableCell>{patient.admission_length}</TableCell>
                      <TableCell>{formatDateTime(patient.last_test_datetime)}</TableCell>
                      <TableCell>
                        {patient.time_since_last_test ? (
                          <Chip
                            label={patient.time_since_last_test}
                            color={getDurationColor(patient.time_since_last_test)}
                            size="small"
                          />
                        ) : (
                          <Chip label="No tests" color="default" size="small" />
                        )}
                      </TableCell>
                      <TableCell>{patient.last_test_name || 'N/A'}</TableCell>
                      <TableCell>{patient.primary_physician || 'N/A'}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              <TablePagination
                component="div"
                count={filteredAndSortedPatients.length}
                page={page}
                onPageChange={(_, newPage) => setPage(newPage)}
                rowsPerPage={rowsPerPage}
                onRowsPerPageChange={(e) => {
                  setRowsPerPage(parseInt(e.target.value, 10));
                  setPage(0);
                }}
                rowsPerPageOptions={[25, 50, 100]}
              />
            </TableContainer>
          )}
        </CardContent>
      </Card>
      </Box>
    </Box>
  );
};

export default Dashboard;
